import type { Metadata } from "next";
import { Anaheim, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header";
import Footer from "@/layouts/footer";
import NextTopLoader from "nextjs-toploader";
import Video_module from "@/Components/Video_Preview";
import Enter from "@/Provider/Enter";

// font form goole
const anaheim = Rubik({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

// meta tags for seo
export const metadata: Metadata = {
  title: "ITAG - IT Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anaheim.className} antialiased`}>
        <NextTopLoader color="#4078ff" zIndex={1600} />
        <Enter>
          <Header />
          <Video_module>{children}</Video_module>
          <Footer />
        </Enter>
      </body>
    </html>
  );
}
