import type { Metadata } from "next";
import { Anaheim } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header";
import Footer from "@/layouts/footer";

// font form goole
const anaheim = Anaheim({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

// meta tags for seo
export const metadata: Metadata = {
  title: "ITAG - IT Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anaheim.className} antialiased`}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
